### ISSUE TITLE
Full text matches and combined relevance score

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/policy-search#30]
Currently, search only returns matches based on embedding similarity. This means that it does not return matches on policy title.

- Matches on policy title where user is looking for a specific policy
- Full text matches where user wants to return specific search terms that match a passage

Embedding similarity is currently not thresholded, but returns top-k results. This means that poor results could be returned for some policies. Investigate the effect of this on the search result quality and how to put in place a configurable threshold to ignore matches below a given threshold.

### Todo 

* [x] Extend the opensearch query to support these full text use cases.
* [x] Investigate the best way to combine matches across full text and embedding to return a combined relevance score
* [ ] Put in place a configurable threshold for embedding similarity

### Requirements for search

* [ ] search results should combine exact text matching with semantic search
* [ ] if searching for a title of a document, that document (or multiple documents with that title) should be returned as the first result.
* [ ] when searching gibberish, no results should be returned (or at least, no english-language results, as there are some non-english language phrases in there). Note that this may be difficult as we are likely to have 'gibberish' sentences in the current corpus.
